### ISSUE TITLE
[bug] Can't get player variable

### ISSUE THREAD

**Issue by yumithecat** [Ajneb97/ServerVariables#2]
When I try to get a player variable by using the /svar get command or the placeholders, I get this error in my console. Is it an error on my side, or is it a plugin error?

![image](https://github.com/Ajneb97/ServerVariables/assets/89903745/b7249b55-3c4a-4fdb-9b44-3e8f85410356)

**Comment by Ajneb97** [comment]
Do you have a lot of player files stored on the plugin folder? One of them is causing the issue, it seems that it doesn't have a player name

**Comment by yumithecat** [comment]
Yeah, for some reason the plugin generates empty files in the players folder.

![image](https://github.com/Ajneb97/ServerVariables/assets/89903745/00219a7d-bc24-49d9-bcbd-603df71c7379)

**Comment by Ajneb97** [comment]
Send me your config please. And have you experienced any crashes on your server? Maybe the data is not being saved correctly. Something like that means that a player joined your server without any name which is impossible as I am aware of.

**Comment by yumithecat** [comment]
I haven't experienced any crashes lately. Here's my config file 

```
config:
  data_save_time: 5
messages:
  prefix: '&3&lNewDale &r&8» '
  commandSetError: '&cYou need to use: &7/svar set <variable> <value> (optional)<player>'
  commandGetError: '&cYou need to use: &7/svar get <variable> (optional)<player>'
  commandAddError: '&cYou need to use: &7/svar add <variable> <value> (optional)<player>'
  commandReduceError: '&cYou need to use: &7/svar reduce <variable> <value> (optional)<player>'
  commandResetError: '&cYou need to use: &7/svar reset <variable> (optional)<player>'
  variableDoesNotExists: '&cThat variable doesn''t exists.'
  variableInvalidValue: '&cThat variable only supports &7%value_type% &ctypes.'
  variableNotPossibleValue: '&cThat variable has these possible values: &7%values%'
  variableSetInvalidTypePlayer: '&cYou can''t set a &7PLAYER &cvariable to the server.'
  variableSetInvalidTypeGlobal: '&cYou can''t set a &7GLOBAL &cvariable to a player.'
  variableGetInvalidTypePlayer: '&cYou can''t get a &7PLAYER &cvariable from the server.'
  variableGetInvalidTypeGlobal: '&cYou can''t get a &7GLOBAL &cvariable from a player.'
  variableResetInvalidTypePlayer: '&cYou can''t reset a &7PLAYER &cvariable from the
    server.'
  variableResetInvalidTypeGlobal: '&cYou can''t reset a &7GLOBAL &cvariable from a
    player.'
  variableAddError: '&cCan''t add a value to a non-numerical variable.'
  variableReduceError: '&cCan''t reduce a value from a non-numerical variable.'
  commandSetCorrect: '&aVariable &7%variable% &aset to &7%value%&a.'
  commandSetCorrectPlayer: '&aVariable &7%variable% &aset to &7%value% &afor player
    &e%player%&a.'
  playerNotOnline: '&cThat player is not online.'
  pluginReloaded: '&aPlugin reloaded!'
  commandGetCorrect: '&aVariable &7%variable% &acurrent value is: &7%value%&a.'
  commandGetCorrectPlayer: '&aVariable &7%variable% &acurrent value from player &e%player%
    &ais: &7%value%&a.'
  invalidValue: '&cYou must use a valid number value.'
  playerNoData: '&cThere is no data for that player.'
  commandResetCorrect: '&aVariable &7%variable% &areset.'
  commandResetCorrectPlayer: '&aVariable &7%variable% &areset for player &e%player%&a.'
variables:
  player_selected_lobby:
    variable_type: PLAYER
    value_type: TEXT
    possible_values:
    - 'lobby_01'
    - 'lobby_02'
    - 'lobby_03'
    initial_value: 'lobby_01'
  player_influence:
    variable_type: PLAYER
    value_type: INTEGER
    initial_value: 0
```
